function status = readStatus(device)

[reply,measurement] = sendSTM32Command( ...
    device,"STATUS",0.50,2,["STATUS="]);

tokens = regexp(reply, ...
    "^STATUS=(-?\d+),(\d+),(\d+),(\d+),(\d+),(\d+),(\d+),(\d+),(\d+)$", ...
    "tokens","once");

if isempty(tokens)
    error("STM32:MalformedStatus", ...
        "Malformed STATUS response: %s",reply);
end

values = str2double(tokens);

status = struct( ...
    "CurrentPWM",values(1), ...
    "CCR4",values(2), ...
    "OverrunErrors",values(3), ...
    "FramingErrors",values(4), ...
    "NoiseErrors",values(5), ...
    "ParityErrors",values(6), ...
    "TxTimeouts",values(7), ...
    "AdcTimeouts",values(8), ...
    "BufferOverflows",values(9), ...
    "RoundTripSeconds",measurement.RoundTripSeconds, ...
    "RawReply",reply);
end