function data = readSTM32Data(device)
%READSTM32DATA Request and validate the combined DATA packet.

pcRequestTime = datetime("now");

[reply,measurement] = sendSTM32Command( ...
    device,"D",0.75,2,["DATA="]);

pcReceiveTime = datetime("now");

tokens = regexp(reply, ...
    "^DATA=(\d+),(-?\d+),(-?\d+),(-?\d+)$", ...
    "tokens","once");

if isempty(tokens)
    error("STM32:MalformedData", ...
        "Malformed DATA response: %s",reply);
end

values = str2double(tokens);

data = struct( ...
    "STM32TimestampMs",uint32(values(1)), ...
    "AngleRaw",values(2), ...
    "Position",values(3), ...
    "AppliedPWM",values(4), ...
    "PCRequestTime",pcRequestTime, ...
    "PCReceiveTime",pcReceiveTime, ...
    "RoundTripSeconds",measurement.RoundTripSeconds, ...
    "IgnoredAlive",measurement.IgnoredAlive, ...
    "RawReply",reply);
end