clear;
clear classes;
clc;

systemObject = [];

try
    systemObject = STM32SerialSystem( ...
        "Port","COM4", ...
        "BaudRate",9600, ...
        "SampleTime",0.10, ...
        "MotorRefreshPeriod",0.40, ...
        "MaximumConsecutiveFailures",3);

    requestedPWM = 0;
    enableMotor = false;
    emergencyStop = true;

    numberOfSamples = 100;

    angleLog = NaN(numberOfSamples,1);
    positionLog = NaN(numberOfSamples,1);
    commandedPWMLog = NaN(numberOfSamples,1);
    appliedPWMLog = NaN(numberOfSamples,1);
    timestampLog = zeros(numberOfSamples,1,"uint32");
    rttLog = NaN(numberOfSamples,1);
    validLog = false(numberOfSamples,1);
    stateLog = zeros(numberOfSamples,1,"uint8");
    successLog = zeros(numberOfSamples,1,"uint32");
    missedLog = zeros(numberOfSamples,1,"uint32");
    malformedLog = zeros(numberOfSamples,1,"uint32");
    consecutiveFailureLog = zeros(numberOfSamples,1,"uint32");

    fprintf("Starting safe System object test.\n");
    fprintf("Motor Enable: false\n");
    fprintf("Emergency Stop: true\n");
    fprintf("Requested PWM: 0\n\n");

    testTimer = tic;

    for k = 1:numberOfSamples

        sampleStart = tic;

        [ ...
            angleLog(k), ...
            positionLog(k), ...
            commandedPWMLog(k), ...
            appliedPWMLog(k), ...
            timestampLog(k), ...
            rttLog(k), ...
            validLog(k), ...
            stateLog(k), ...
            successLog(k), ...
            missedLog(k), ...
            malformedLog(k), ...
            consecutiveFailureLog(k)] = ...
            systemObject( ...
                requestedPWM, ...
                enableMotor, ...
                emergencyStop);

        elapsedInSample = toc(sampleStart);
        remainingTime = 0.10 - elapsedInSample;

        if remainingTime > 0
            pause(remainingTime);
        end
    end

    totalElapsedSeconds = toc(testTimer);

    release(systemObject);

    results = table( ...
        (1:numberOfSamples)', ...
        angleLog, ...
        positionLog, ...
        commandedPWMLog, ...
        appliedPWMLog, ...
        timestampLog, ...
        rttLog, ...
        validLog, ...
        stateLog, ...
        successLog, ...
        missedLog, ...
        malformedLog, ...
        consecutiveFailureLog, ...
        'VariableNames',{ ...
            'Sample', ...
            'AngleRaw', ...
            'EncoderPosition', ...
            'CommandedPWM', ...
            'AppliedPWM', ...
            'STM32TimestampMs', ...
            'RoundTripMs', ...
            'DataValid', ...
            'ConnectionState', ...
            'SuccessfulPackets', ...
            'MissedPackets', ...
            'MalformedPackets', ...
            'ConsecutiveFailures'});

    fprintf("\nSYSTEM OBJECT TEST SUMMARY\n");
    fprintf("Total samples:          %d\n",height(results));
    fprintf("Valid samples:          %d\n",sum(results.DataValid));
    fprintf("Invalid samples:        %d\n",sum(~results.DataValid));
    fprintf("Mean DATA RTT:          %.3f ms\n", ...
        mean(results.RoundTripMs(results.DataValid)));
    fprintf("Maximum DATA RTT:       %.3f ms\n", ...
        max(results.RoundTripMs(results.DataValid)));
    fprintf("Final successful count: %d\n", ...
        results.SuccessfulPackets(end));
    fprintf("Final missed count:     %d\n", ...
        results.MissedPackets(end));
    fprintf("Final malformed count:  %d\n", ...
        results.MalformedPackets(end));
    fprintf("Total elapsed time:     %.3f seconds\n", ...
        totalElapsedSeconds);

    fprintf("\nFinal five samples:\n");
    disp(results(end-4:end,:));

catch ME
    fprintf(2,"\nSYSTEM OBJECT TEST FAILED\n");
    fprintf(2,"Identifier: %s\n",ME.identifier);
    fprintf(2,"Message: %s\n",ME.message);

    if ~isempty(systemObject)
        try
            release(systemObject);
        catch
        end
    end

    rethrow(ME);
end

clear systemObject;

pause(0.25);

fprintf("\nAvailable ports after releasing System object:\n");
disp(serialportlist("available"));